---
- hosts: local
  connection: local
  gather_facts: no
  tasks:

      - name: Create a new EC2 instance
        ec2_instance:
            name: cc-interview-rahul
            key_name: "cc-interview-rahul"
            vpc_subnet_id: subnet-79cf2910
            instance_type: t2.nano
            security_group: sg-c61ab8af
            network:
               assign_public_ip: true
            image_id: ami-06c4efeb2f3264d9b
            region: ap-south-1
            aws_access_key: XXXXXXXXXXXXXXXXXXXX
            aws_secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        register: ec2_instance_result
      
     # - debug: 
      #    var: ec2_instance_result
      - name: Save IP address
        add_host:
          hostname: "{{ item.public_ip_address }}" 
          groupname: ec2_instance_ips
        with_items: "{{ ec2_instance_result.instances }}"     


- name: installing and configuring nginx on spawned ec2-instance
  hosts: ec2_instance_ips
  vars:
    ansible_ssh_private_key_file: cc-interview-rahul.pem
    ansible_user: ec2-user 
  roles:
    - nginx
  become: yes
