---
- hosts: local
  connection: local
  gather_facts: no
  tasks:

      - name: Create a new EC2 key
        ec2_key:
            name: cc-interview-rahul
            region: ap-south-1
            aws_access_key: XXXXXXXXXXXX
            aws_secret_key: XXXXXXXXXXXXXXXXXXXXX
            key_material: "{{ lookup('file', 'cc-interview-rahul.pub') }}"
        register: ec2_key_result
